# Created with WinGet Releaser main using Komac v1.0.5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Telegram.TelegramDesktop
PackageVersion: 4.9.4
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: Telegram\Telegram.exe
  PortableCommandAlias: telegram
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- tg
ReleaseDate: 2023-08-31
Installers:
- Architecture: x86
  InstallerType: zip
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v4.9.4/tportable.4.9.4.zip
  InstallerSha256: FC63B1660D8B5E39D2556ECAF627F36177FF587B00F666BC8D4191E585C83073
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v4.9.4/tsetup.4.9.4.exe
  InstallerSha256: 96F4D9BF942EA49598EACF904DC94362B94643975E099167404DEA074028D3A6
- Architecture: x64
  InstallerType: zip
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v4.9.4/tportable.4.9.4.zip
  InstallerSha256: FC63B1660D8B5E39D2556ECAF627F36177FF587B00F666BC8D4191E585C83073
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v4.9.4/tsetup-x64.4.9.4.exe
  InstallerSha256: 8D9FC09BE8F851AB9B3CD33C100F5C1609561A070E61E1B6A2F2988138695BB9
ManifestType: installer
ManifestVersion: 1.4.0
