# Created with WinGet Releaser main using Komac v1.0.5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Telegram.TelegramDesktop
PackageVersion: 4.9.4
PackageLocale: en-US
Publisher: Telegram FZ-LLC
PublisherUrl: https://telegram.org
PublisherSupportUrl: https://telegram.org/support
PrivacyUrl: https://telegram.org/privacy
Author: Telegram FZ-LLC
PackageName: Telegram Desktop
PackageUrl: https://desktop.telegram.org
License: GNU-3.0-only
LicenseUrl: https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/LICENSE
CopyrightUrl: https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/LICENSE
ShortDescription: Telegram is a cloud-based mobile and desktop messaging app with a focus on security and speed.
Tags:
- chat
- messaging
- messenger
ReleaseNotes: |-
  - Default private chats / groups / channels notification settings.
  - Forwarded / reply-to-a-story icon in chats list message preview.
  - Bug fixes and other minor improvements.
ReleaseNotesUrl: https://github.com/telegramdesktop/tdesktop/releases/tag/v4.9.4
ManifestType: defaultLocale
ManifestVersion: 1.4.0
